const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Audio.Acts.UnloadAudio,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.ScriptsInEvents.FolhaDeEventosFase1_Event21_Act3,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoFase1: 0},
	{Sólido: 0},
	{Chão: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Kensei: 0},
	{Teclado: 0},
	{Parede_Invisivel: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos: 0},
	{FonteDeSprites: 0},
	{jogar: 0},
	{historia: 0},
	{Mouse: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{voltar: 0},
	{FonteDeSprites3: 0},
	{fundovida: 0},
	{barradevida: 0},
	{direcao: 0},
	{Piscar: 0},
	{inimigo: 0},
	{parede_inimigo_direita: 0},
	{parede_inimigo_esquerda: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{FonteDeSprites2: 0},
	{tente_novamente: 0},
	{desistir: 0},
	{limbo: 0},
	{espinho: 0},
	{Sprite: 0},
	{chao_falso: 0},
	{Sprite2: 0},
	{FonteDeSprites4: 0},
	{Oniroshi: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Sprite3: 0},
	{voltar_inicio: 0},
	{FonteDeSprites5: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Vidas: 0}
];

self.InstanceType = {
	PlanoDeFundoFase1: class extends self.ITiledBackgroundInstance {},
	Chão: class extends self.ISpriteInstance {},
	Kensei: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Parede_Invisivel: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	jogar: class extends self.ISpriteFontInstance {},
	historia: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	voltar: class extends self.ISpriteFontInstance {},
	FonteDeSprites3: class extends self.ISpriteFontInstance {},
	fundovida: class extends self.ISpriteInstance {},
	barradevida: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	parede_inimigo_direita: class extends self.ISpriteInstance {},
	parede_inimigo_esquerda: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	tente_novamente: class extends self.ISpriteFontInstance {},
	desistir: class extends self.ISpriteFontInstance {},
	limbo: class extends self.ISpriteInstance {},
	espinho: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	chao_falso: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	FonteDeSprites4: class extends self.ISpriteFontInstance {},
	Oniroshi: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	voltar_inicio: class extends self.ISpriteFontInstance {},
	FonteDeSprites5: class extends self.ISpriteFontInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}